### ISSUE TITLE
Catch all wifi APs that come in if we have a gps position

### ISSUE THREAD

**Issue by dicer** [n76/wifi_backend#12]
While debugging a bit, I noticed that the WiFiSamplerService:WifiSampleReceiver receives a lot of wifi samples, but often isScanStarted() returns false. I guess this is because GPS location and wifi scanning is asynchronous and other apps on the phone initiate wifi scans.
Depending on what applications are running or which other UnifiedNLP plugins you have running one might miss quite a few samples.

So I was thinking: Can't we save the time of the GPS fix and for the next X seconds, we take all the samples we get and add them to the database? Not sure what X should default to, but I guess a few seconds won't hurt.

What do you think?

**Comment by n76** [comment]
Sounds like a good idea. I will look into it.
