### ISSUE TITLE
How to edit the database?

### ISSUE THREAD

**Issue by borad2** [n76/wifi_backend#14]
Is there a way to edit (or add/remove) entries in the database?
I have found the wifi.db which i can edit under Windows. But the .db-shm and .db-wal are deleted by that sqlite-programm and the database is broken for the wifi_backend.

**Comment by n76** [comment]
At present I don't have a way to edit the database. You can, if needed, use the application manager to clear out all of the data used by the backend. I'd suggest disabling it prior to doing that.

What is your use case, that is what has happened that you need to edit the database?

**Comment by borad2** [comment]
Its just for manual correction/add of known accesspoints.

**Comment by borad2** [comment]
I thought that the database is defective because 987654321 Access Points were displayed. I have found that I have to wait a bit until the database reloaded. You can use a simple SQLite database editor to edit the database.
