### ISSUE TITLE
Import external database in version 1.0.0

### ISSUE THREAD

**Issue by jw243** [n76/wifi_backend#28]
I have played around with the import/export function in version 1.0.0. However, it only seems to understand .json files. That probably means, it is rather a backup function, allowing to backup collected data and to reload it back into the backend at a later time.

It would be nice, however, if one could add additional data from an external database such as from radiocells.org. They provide their database either in .sqlite or .csv format. It would be great if one could add those data (and even upload the collected data back to radiocells.org).

Wouldn't a cooperation between this project and radiocells.org / openbmap.org be a nice idea?

By the way, when I use the import function, will the existing data be overwritten or appended?

**Comment by n76** [comment]
Looking at radiocells.org, it would seem that importing the daily csv file would be most useful. I'll put that on my list of things to do. One issue might be size: It seems unlikely that you'd want the entire world on your phone (currently over 7 million records), so some sort of location filtering is probably desirable.

With respect to exporting data for radiocells.org, I don't see anything on their website that allows for data other than that collected through their app. Looking at some of the raw data files, there are a number of items I specifically don't collect, so even if they would allow upload of WiFi AP location data I am not sure this backend is a good data collector for that.

**Comment by jw243** [comment]
I have already suggested to radiocells.org to start splitting the database into regional sub-databases. This will probably be inevitable soon looking at the graph of the growth of the dataset on their web page. Within the last year, the size of the file has quadrupled!

I really like the newest version of your backend. Nice design and it works really well.

**Comment by maumi** [comment]
The openbmap plugin always crashes on my mobile. So I tried to filter out APs by the coordinates to only import the ones from my home city.
I tried to import my "own" json file. For testing purposes, I only wrote an json file with only one entry.
the whole file looks like:
[{"bssid":" 925F2ED0713D ","samples":[{"lat": 52.34150531 ,"lon": 9.41839906667 }]}]
and is named foo.json
but it seems that I can only import the APs which I exported before.
All other files including my foo.json are greyed out.
Is this done by purpose or an error?

**Comment by n76** [comment]
There should be nothing stopping the back end from importing a JSON file written by another application or script. The import logic will only overwrite an existing point in the database if the perimeter (coverage radius) of the AP in the JSON file is larger. The perimeter of your sample is zero as you only have one lat/lon sample, so if that bssid already exists in the database it will be ignored.

**Comment by maumi** [comment]
Strange. On my S5 I can only select and import a file which I exported before into the download-tab.
On Samsung mobile you have tabs on the left with 
last (used folders)
Download (only new downloads in internal download folder are displayed)
Internal memory
External sd card
When I use the download tab for export the created json is not greyed out and I can select it for import.
But when I try to import same file with tab internal memory/download it is greyed out and not selectable. So maybe a samsung bug.

**Comment by pvagner** [comment]
I'm running CM-13 on a Samsung GTI9100 and I can't import json files stored on my internal storage. The file is named wifi.json and when browsing to it it's greyed out like @maumi says. I'll try to save a file, replace it with the old backup to see if i'll be able to import it that way. BTW my file is a backup from this app running on SlimLP a few days ago.

**Comment by fellek** [comment]
Confirming what @maumi and @pvagner said before on Nexus 4 and Samsung S3mini. 
I've tried to sync backend-data just importing the backup from booth phones, but it needed a workaround: 

Export to tab "Downloads" > wifi.json
Remove file "wifi.json" 
Copy & Paste file you want to import into same folder
Rename it "wifi.json"
Import from tab "Downloads" < wifi.json
Done

Attention: Don't be confused, the filesize inside the import-dialog will show not the size from current file, but the original export-file size. 

Works @ Nexus 4 (CM13), S3mini (CM12) 

@n76 it seems that export/import routine writes some cache and is not really looking for some json files.
Nevertheless, its a great app and I appreciate the wifibackend!

**Comment by n76** [comment]
Looks like the Android MimeTypeMap does not have an entry for JSON so content providers (i.e. file system browser) won't allow you to select a .json file. There is a content type for comma separated value (csv) files and that looks like a better format for sharing/importing data from other projects. I'll drop the JSON format in favor of a CSV format that uses headers compatible with radiocells.org / openbmap.org. However this will probably only work for backup and import as the backend does not collect all the fields those organizations have.

**Comment by maumi** [comment]
I would prefer xml over csv because it's a cleaner structure if we export always 3 lat/long per bssid. Also if we want to add later additional informations to AP it would be a crap with csv.
Even if there are backup tools for Android its not said that people use them (want to use them). I don't use any and I'm happy to have a simple backup here.
I think the export to other databases shouldn't be so hard but the import. I think most databases only save one lat/lon per AP.
What I do is taking a full sqlitedb from radiocells and filter it on pc and put it on my mobile again. Same with mozilla and opencellid. On phone I use the 3 backends. Not the comfy way but it works.
To share collected APs I like the idea of a "private" sharing. So nothing with one big database more like a thread where people say: "hey I live in germany and I would like to share mainly this city ...".
The main idea for the most of us is to get away from big data crawlers like google and that's why we are here. And I don't need APs from australia if I never travel there pe.
To the partial update, I think in most use cases it's not necessary because we have 5k-50k APs and the export file would still be under 1MB.

**Comment by jw243** [comment]
I have recently switched to an Android phone in addition to the Android tablet I already owned. On the phone, I installed your GSM backend and I am very impressed. The database import function is amazing. It would be awsome, if the import function in the Wifi backend could be implemented in a similar convinient way, i.e. download of preconfigured regional databases (like lacells) as well as download of a complete database that is being filtered for region on the fly.

Absolutely great job!

**Comment by jw243** [comment]
Since you closed this issue, is it now possible to import external wifi data from some kind of database?

I still like the idea to have an import function similar to that in your GSM backend, where one can import data with the touch of a button.

**Comment by n76** [comment]
See the comments under export and import on the [GitHub page for this backend](https://github.com/n76/wifi_backend).

You should be able to import data from another project but you may have to pre-process their data to be useful. Specifically, this backend needs three location data points per AP and many projects simply give a single centroid location. To be useful in this backend you will have to covert the single location into three locations that correspond reasonably well to the expected coverage radius of the AP.

**Comment by jw243** [comment]
And what about the idea of a one-click import function of preconfigured data such as in your GSM backend?

**Comment by Lee-Carre** [comment]
@jw243

> what about the idea of a one-click import function of preconfigured data such as in your GSM backend?

There's a separate backend (“Merged Wi-Fi Location Service”) which reads CSV files you supply, to compute a position. The preparation & transfer of suitable CSV could an scripted. Sounds like that does what you want.

See also #3.
