### ISSUE TITLE
Backend needs to be re-activated after change of location-state

### ISSUE THREAD

**Issue by maumi** [n76/wifi_backend#30]
Normally my mobile is in nongps-location-state. I switch gps on and off with e-robot when certain apps are opened. When I want to collect APs I start a gps tracking activity. Most of the time I need to switch the backend off and on again after my gps is switched on. Otherwise no new APs are collected. Haven't found useful things in logcat.

**Comment by n76** [comment]
Interesting. . . The backend AP collection requests position updates with a PASSIVE_PROVIDER and then ignores any position other than an accurate enough one from the GPS provider.

http://developer.android.com/reference/android/location/LocationManager.html#PASSIVE_PROVIDER

I don't see anything in the documentation indicating that the listener must be restarted if the providers available to the system has changed. I'll have to research this more.

**Comment by n76** [comment]
I have been unable to duplicate this. Is it still occurring? What version of Android are you using?

**Comment by maumi** [comment]
I think it's still occuring. Was using CM13 (Android 6.0) but Last time I didn't switched gps Off. 
And now I'm unable to Test because I switched back to Stock based custom Rom.
So I'm closing issue for now and when I'm using it again and gets the issue I will Open it again with a Log attached.
