### ISSUE TITLE
Gathering wifi database from end-users.

### ISSUE THREAD

**Issue by bharat226g** [n76/wifi_backend#33]
This backend is great and gives much much better accuracy than other wifi location providers. 

I wish there is database collection from this app and contributing to a common database available publicly under some open license. So one can download much wider accurate data, filter it and import it into this app for a better location. Later maybe someone will split up the data and provider as regional database, like in LocalGsmBackend. If it bloats this, maybe as a separate wifi stumbler application with accuracy and other parameters same as this app. 

Helps a lot. Any plans?

**Comment by n76** [comment]
Backend will not directly support submitting data to or importing data from other projects but the change to the import/export function in v1.1.0 should allow users to do this if they wish.
