### ISSUE TITLE
Sometimes the backend gives a NaN coordinates

### ISSUE THREAD

**Issue by demecoandrea** [n76/wifi_backend#34]
I have this issue on a Samsung Galaxy SIII Mini (i8190N).
I tested the location with a little app, "Here GPS Location" that shows separately the (phisical) GPS coords and the network coords. On about 10% of the location update (randomly) gives me:

Latitude = NaN
Longitude = NaN
Accuracy = 20.412215

I used CyanogenMod 11 (kk4.4.4) and I thought it was some kind of OS incompatibility.

Today I installed the CM12, I installed xposed, unified nlp, and the last version of the personal WiFi backend (v1.0.1). 
The % of the NaN events has decreased, but sometimes it still appears.

![9e720465-3f55-4599-8d2e-868a874669c2](https://cloud.githubusercontent.com/assets/15663607/15230047/2648d2d4-1894-11e6-8897-20eb123a25b0.jpg)

this is the logcat file (I hope I did it well...)
[logcat1.txt](https://github.com/n76/wifi_backend/files/262240/logcat1.txt)
a "NaN" event is on line 11123

**Comment by n76** [comment]
I have not seen this in my log files, so I hope you can work with me on this.

First, if you export the database do the lat/lon values seem reasonable? Basically none with zero values and the range in latitude and longitude about what you would expect for where you have had your phone. I suspect/hope the sampling side of things is okay but need to confirm that.

If the sample database looks reasonable, then I'd like to give you a debug version of the apk that has some logging turned on that will give me a better idea about what is going on. At first glance the only area I may not have been careful enough about checking values is with the signal strength indicator but nothing about that is logged at the moment in the release apk.

**Comment by demecoandrea** [comment]
Thanks for your fast reply.

I tried with the simplest database I could build, just one position, my house.

This is the JSON exported with the backend

(did you mean this one? i renamed the extension from "json" to "txt" in order to upload here)

[wifi CR.txt](https://github.com/n76/wifi_backend/files/262337/wifi.CR.txt)

**Comment by n76** [comment]
The data in that file looks reasonable (all lat/lon values in a cluster, etc.)

Next issue is that I've changed the import/export format. The APK I'll give you will be signed by me instead of F-Droid which means that you will have to uninstall your current version to install mine. And, unfortunately, it appears that F-Droid does not have v1.1.0 available yet so you can't update to that and the export your data as comma separated values. End result, you will lose your existing data. Do you have an issue with that?

**Comment by demecoandrea** [comment]
No problem, I don't care of losing data.. I haven't a big DB.

If it can help, i have other 8 devices, and it works perfectly on each of them.
(5 smartphone cinese mtk, an allwinner tablet, and a nexus 5)
The only one that gives this issue is the Samsung S3 mini.
I hope you don't do a lot of efforts to correct this issue, maybe it exists on this kind device only..

Just, if you can, you could add something like this at the output of everything

if(outputValue.isNaN()){
     //try to calculate again or just
     //output the previous valid value
}

**Comment by n76** [comment]
If worse comes to worse, I'll put in something like that check for NaN but I'd rather figure out what is happening.

I've put an apk at https://dl.dropboxusercontent.com/u/19663978/app-release.apk which should be exactly the same as my current v1.1.0 release but with some logging enabled. If you can capture some of the log with something like:

> adb logcat | grep WiFiBackendLocationUtil

I would appreciate it.

**Comment by demecoandrea** [comment]
sure :) thanks again!
I installed your apk..
I'll upload the logcat as soon as the issue comes out again

**Comment by demecoandrea** [comment]
Here we are.. I caught the issue again, and I did a logcat.

(I'm sorry for the verbose log, I'm on windows 7 and I don't know what's the grep alternative.. if it's a problem I'll use some external program to filter the strings)

[wifi4.txt](https://github.com/n76/wifi_backend/files/263564/wifi4.txt)

**Comment by n76** [comment]
I think I've got it fixed. I've put an updated copy at https://dl.dropboxusercontent.com/u/19663978/app-release.apk so you can use it now and not wait for F-Droid to pick up the new version.

**Comment by demecoandrea** [comment]
Thankssssssss a LOT :D :D I'm trying it immediately :)

**Comment by n76** [comment]
Let me know if there is still an issue, if so I will re-open this and we can work on it some more.
