### ISSUE TITLE
WiFi Location Service and Android 6.0.1

### ISSUE THREAD

**Issue by tecufanujacu** [n76/wifi_backend#37]
I'm using this backends with microg on cm13 and I have two questions:
- to correctly use this backend have I to enable the voice: Settings -> Location -> Scanning -> Wi-Fi scanning?
- is it normal that in AppOps under the Location tab I see that WiFi Location Service always runs?

**Comment by n76** [comment]
I am using a AOSP 6.0.1 build so I cannot answer about CM specific items.

• My AOSP does not have anything under Settings -> Location where you you can set "Scanning" for WiFi (or anything else). The app checks if WiFi is enabled and if not, if WiFi scanning is available when WiFi is disabled before trying to scan. If CM is doing something to change the results given by calls to isScanAlwaysAvailable() then it could make a difference.

• Yes, the WiFi backend will always be on the recent location users. The WiFi backend does a "passive" location lookup request. Basically that says that it is requesting a location update from any source (GPS, network, etc.) but don't actually start the GPS or network location subsystems. If any other app requests those services, then the WiFi backend will get the results too. The end result is that if no other app requests those services the WiFi backend will simply be registered as a listener but no other overhead (battery use, CPU cycles, etc.) are being used.
