### ISSUE TITLE
include other wifi parameters in database.

### ISSUE THREAD

**Issue by bharat226g** [n76/wifi_backend#38]
I think the database only uses the fields bssid , lat , lon , ssid .

I would like to request to include more wifi parameters like 

channel
speed - 54 / 54e .
encryption - open / wep / wpa / wpa2 .
cipher - TKIP / CCMP .
auth - psk .
gps accuracy.

Since there is no in-app option to contribute the data to a centralized server, I think its safe to include those parameters. So, people can know better about the wifi networks around them.

Thanks.

**Comment by n76** [comment]
That is quite a bit of additional data to store about all WiFi/WLAN APs a phone has seen. :)

At present my focus is to add other types of RF (cell/mobile, bluetooth) to the database and location algorithm to improve the range of situations that this backend can provide position information for. Turning it into a general purpose WiFi stumbler is not on my roadmap.

**Comment by Lee-Carre** [comment]
I concur that the backend should be kept minimal and store only what it needs for doing positioning.

Other apps exist for comprehensive network surveying; see [#7 (comment)](/n76/wifi_backend/issues/7#issuecomment-1040522234):
> I've considered using your backends for general (surveying) data collection of radios, but they log only the minimum for positioning (which makes sense, and don't expect that to change; smaller DB for the efficiency win), whereas I'm something of a greedy data-whore wanting to capture all characteristics & many samples. For network surveying, I use a dedicated collection-only (no processing / filtering, or submitting-to-projects) app (aptly called Network Survey), and (will eventually) process its output separately (e.g. for uploading to projects).
