### ISSUE TITLE
Library module

### ISSUE THREAD

**Issue by dataluminosity** [n76/wifi_backend#42]
It would be useful if this project separate out the UI components and services such that it can be re-used in other Android apps as a library module.

This would be for doing location lookups without utilizing Google Play on non-rooted Android phones. Basically, using the local wi-fi database and gps to determine location.

**Comment by n76** [comment]
This is a backend for the UnifiedNLP, so really the request is for a version of UnifiedNLP that can run in the environment you describe. I believe that already exists, at least there is a version on F-Droid that seems to have that description.
