### ISSUE TITLE
XML uninterpreted with the French translation on home screen

### ISSUE THREAD

**Issue by Massedil** [n76/wifi_backend#49]
In wifi_backend freshly translated in French, the app's home screen has a bad translated string which seems to contain an XML data. But the XML seems to be uninterpreted.

![1](https://user-images.githubusercontent.com/20357783/30540197-5d1f564a-9c76-11e7-9fcd-42aad55ee177.png)

**Comment by ArchangeGabriel** [comment]
Same as [here](https://github.com/n76/Local-GSM-Backend/issues/100), but you know that. So the fix will be similar: https://github.com/n76/Local-GSM-Backend/commit/630acfef04138ee2ad42d18456b48b547685a769

**Comment by n76** [comment]
Fixed in v1.1.9
