### ISSUE TITLE
Option to examine/reset wifi APs DB ?

### ISSUE THREAD

**Issue by breversa** [n76/wifi_backend#5]
Hi there,

Is there an option to see what APs are stored in the local DB ? And, if appropriate, delete some or all of them ?

On my Galaxy Nexus (maguro) with CyanogenMod 11 M12, I sometimes get less accurate position when using "high precision" location rather than GPS only (about 50-200m off when I'm at home :-( ), and I believe I might be able to help troubleshoot that issue which such a feature.

**Comment by n76** [comment]
Definitely a bug if WiFi is returning a higher accuracy position than GPS. I am be very interested in what logcat shows for that. 

Are you able to build your own copy of the backend? If so, in configuration.java set DEBUG = DEBUG_VERBOSE and build it. If not, let me know and I will get you a debug version for you to try. 

Unfortunately, I think if you switch sources (F-Droid to local debug build) you might lose the database so the symptoms might change.

**Comment by breversa** [comment]
I actually may have used the wrong words to describe my experience, so here I go again :

From my place's window, using GPS only, I usually get an accurate fix (< 10-20m radius) in less than a minute, sometimes 12-15 seconds.

I started experimenting with Unified NLP last week, and with wifi/network only, I got an even faster fix (like 2-4s), but much less accurate (about 50-100m radius) fix. However, the position I got was off by 50-200m (to the north).

With both GPS + wifi/network, I got pretty much the same result as with wifi/network only. However, I did not check the satellites' reception, so it's possible that I actually had no GPS fix and only relied on wifi/network.

Bottom word : I need to do more tests and compare position and accuracy in regard with the satellites' reception.

I won't be able to test in the same circonstances before march, but I'll let you know nonetheless. I'm no Java coder and can't build, but I'd happily test any build you'd give me. :-)

Until then, I guess I'll just keep MozStumbling cell towers and wifi APs to improve the local coverage ! ;-)

**Comment by n76** [comment]
A position with a reported (bug possibly erroneous) accuracy of 50 or more meters is entirely plausible. If you turn on something that uses the GPS and wander around your neighborhood the backend will collect more WiFi AP location data and the position it returns should become better.

I am going to close this now, but feel free to reopen if this explanation is not enough.
