### ISSUE TITLE
Show status of WiFi database in settings

### ISSUE THREAD

**Issue by Susurrus** [n76/wifi_backend#6]
Would be useful for people to know how well this is working. Just display the total number of APs and/or samples being stored as well as the last time that database was updated with new ones.

Since this works passively and requires the phone to have an accurate GPS lock, which may require an app starting this process, it'll help users make sure the app is working.

**Comment by n76** [comment]
Sounds useful. I will go ahead and add number of APs in the database to the bottom of the settings page.

In the mean time you can go to the system Settings->Apps and look at the data memory used by "WiFi Backend" to get a general feel. For example today my phone is showing data storage of 9.03MB and, by internal inspection, has 57497 APs (approximately 165 bytes/AP).

There is only one table in the database which holds three samples per AP record. The collection algorithm tries to find the perimeter of the AP coverage area, defined by the largest triangle it can make from  samples it sees from each AP.

If you want to examine the database itself, you can pull it from the phone:

> adb root
> adb pull /data/data/org.fitchfamily.android.wifi_backend/files/wifi.db
> adb pull /data/data/org.fitchfamily.android.wifi_backend/files/wifi.db-shm
> adb pull /data/data/org.fitchfamily.android.wifi_backend/files/wifi.db-wal
> sqlite3 wifi.db
sqlite> .tables
sqlite> .schema APs
sqlite> select count(*) from APs;
sqlite> .quit

**Comment by n76** [comment]
Pushed change for v0.11.1 to show number of known APs in settings.
