### ISSUE TITLE
WiFibackend doesn't seem to run

### ISSUE THREAD

**Issue by Susurrus** [n76/wifi_backend#7]
With the latest updated to UnifiedNlp I've been able to get the local gsm back end to run. But I'm unable to get the local WiFi back end to record any access points. I've biked/driven around town running MozStumbler, which is recording WiFi and cell tower info just fine.

So 2 questions:
  * is there any debugging info sent to the log? If so, what should I filter for?
  * what's the best way to make sure the local WiFi back end can record data? Can I just leave my GPS and WiFi on or do I need to use another app like Osmand to make sure the GPS stays active? This info should probably also be added to the readme.

**Comment by n76** [comment]
The sampling portion of the WiFi backend uses the "passive provider" described at http://developer.android.com/reference/android/location/LocationManager.html#PASSIVE_PROVIDER

It will use updates from the GPS if some other app is actually got the GPS turned on and is using it. It will not actually turn on the GPS itself (the intent was to keep power usage low and running the GPS is a power intensive operation).

I usually have OsmAnd turned on, but other software that uses the GPS should work too.

I will add a bit more explanation to the readme for this backend.

**Comment by n76** [comment]
Question: Would it be useful for the data collection to occasionally fire up the GPS in addition to passively monitoring location? Perhaps one sample every 1/2 hour?

**Comment by Susurrus** [comment]
It might be nice to have a setting for it to bet either active or passive. This would allow people to use the provider itself to get the data they need or, if they commonly use a mapping app or some other GPS user, they would be able to piggy-back off that.

**Comment by Susurrus** [comment]
I'm still seeing this problem and have 0 APs recorded. I even enabled the wifi option for allowing for scanning when wifi is off or whatever that one is.

If I look through the phone logs what term can I search through to find debugging info about this backend?

**Comment by n76** [comment]
From what you write, I can only think of three situations:
1. There are no WiFi APs in your area with names that don't block recording (suffix of "_nomap", etc.)
2. You have not achieved a GPS position at least as accurate as specified on the WiFi backend's settings (default of 10 meters) while in an area with WiFi APs.
3. For some reason the WiFi backend is not starting.

Are there any WiFi APs in your area that do not have SSIDs with names including things like "_nomap"? If so, can you enable some application that uses the GPS, like OsmAnd or OSMtracker, verify that you have a multiple satellites locked, run it for a while. After that, look on the WiFi backend settings page and see what the AP count is.

At present, most debug logging is disabled in the backend. If the above does not work for you, I will create a build with more logging enabled and give you a link to it.

**Comment by Susurrus** [comment]
I believe it's number 3 because if I use SatStat, which is awesome BTW, I can see my GPS accuracy is 3m here. I'm actually in my house getting an error of 3m connected to 12 satellites. I can also use MozStumbler to see how many APs and GPS satellites it finds and it's doing  Additionally, my phone itself is on a network named "NETGEAR04-5G". So if this thing is working correctly I should have at least 1 AP in my list, but I'm not getting any.

**Comment by n76** [comment]
Okay, here is a copy of the WiFi backend that has debugging turned on and some additional debug logging added: https://dl.dropboxusercontent.com/u/19663978/wifi_backend-debug.apk

You should be seeing things like:
```
$ adb logcat | grep wifi-backend-SamplerService
D/wifi-backend-SamplerService(18257): service started
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[network 3n.nnn286,-12n.nn2030 acc=1163 et=+20d5h37m53s749ms {Bundle[mParcelledData.dataSize=764]}])
D/wifi-backend-SamplerService(18257): Ignoring position from "network"
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=15 et=+20d5h37m58s846ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (15.0 meters).
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=20 et=+20d5h38m3s876ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (20.0 meters).
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=25 et=+20d5h38m8s888ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (25.0 meters).
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=35 et=+20d5h38m13s891ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (35.0 meters).
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=50 et=+20d5h38m18s799ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (50.0 meters).
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[network 3n.nnn978,-12n.nn3003 acc=187 et=+20d5h38m23s749ms {Bundle[mParcelledData.dataSize=1780]}])
D/wifi-backend-SamplerService(18257): Ignoring position from "network"
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=50 et=+20d5h38m28s839ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (50.0 meters).
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=50 et=+20d5h38m33s871ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (50.0 meters).
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=50 et=+20d5h38m38s780ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (50.0 meters).
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=50 et=+20d5h38m43s797ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (50.0 meters).
D/wifi-backend-SamplerService(18257): onLocationChanged(Location[gps 3n.nnn818,-12n.nn3027 acc=50 et=+20d5h38m48s782ms alt=-15.29998779296875 vel=0.0 bear=32.0 {Bundle[mParcelledData.dataSize=540]}])
D/wifi-backend-SamplerService(18257): Ignoring inaccurate GPS location (50.0 meters).
```
Lat/Lon munged for a little obscurity. :)

If you see nothing with that grep filter, then use "wifi-backend" for the filter string.

**Comment by Susurrus** [comment]
So, that version worked great. After I started it up and ran it briefly it found 35 APs. Then turning on battery saving location I was able to use that back end to find GPS coordinates.

What's funny though is that I uninstalled it and reinstalled the F-droid version and that one still doesn't work for me. I wonder if there's a bug where only if it logs some data does it actually get activated.

**Comment by n76** [comment]
I bump the version number each time I push to github and it looks like F-Droid is offering the last version I pushed. For the version I gave you I rewrote one if statement to allow more detailed logging and changed a couple of log messages. There should have been no functional changes.

**Comment by n76** [comment]
Pushed a new version to github that allows user to enable logging from settings. See what that shows when F-Droid picks it up.

**Comment by dicer** [comment]
I got the same situation here. master build from yesterday. Debugging level in prefs set to 3. Lot's of scanning happening, other apps do find APs and quality of GPS is very good. Actually that's the only option besides debug I changed (to 13).

Still: No entry in the database. Lots of these in the log though:

I/wifi-backend-WiFiReceiver( 7420): Got 9 wifi access points
I/wifi-backend-samplerDatabase( 7420): ApLocation negative cache: 1ms
I/wifi-backend-samplerDatabase( 7420): ApLocation negative cache: 0ms
I/wifi-backend-samplerDatabase( 7420): ApLocation negative cache: 0ms
....
I/wifi-backend-backend-service( 7420): WifiDBResolver.process(): No APs with known locations
I/wifi-backend-backend-service( 7420): update()
I/wifi-backend-backend-service( 7420): update(): Starting scan for WiFi APs
I/wifi-backend-backend-service( 7420): update()
I/wifi-backend-backend-service( 7420): update(): Starting scan for WiFi APs

I also checked directly inside the /data/data/org.fitchfamily.android.wifi_backend/files/wifi.db
The APs table is completely empty.

Haven't had the time to debug this. It does not seem to be debug logging though. Well, actually I only get Info-Logs and nothing for grep wifi-backend-SamplerService

**Comment by dicer** [comment]
I think I found the solution to this issue. I added some debugging code and all of a sudden things started working. First APs in DB after having this running for over 2 months. So I figured it gotta be a race condition. I added more logs and I'm pretty sure I found the problem. With this fix I actually got it working without any additional debug code or debug even on.

**Comment by n76** [comment]
Thank! I guess with my phone this is something that never occurred. I'll make a commit with a new version number to close this issue.

**Comment by Lee-Carre** [comment]
> what's the best way to make sure the local WiFi back end can record data? Can I just leave my GPS and WiFi on or do I need to use another app like Osmand to make sure the GPS stays active?

> other software that uses the GPS should work too

Easiest way I've found is (from [n76/DejaVu#25 (comment)](//github.com/n76/DejaVu/issues/25#issuecomment-1040310105)):
> There are apps which have a feature to toggle GNSS on (and keep it enabled), without doing much more (low memory usage).
> * [OpenTracks](//www.f-droid.org/packages/de.dennisguse.opentracks) (`Start G[NS]S`, which is distinct from starting to record a track)
> * [My Location](//www.f-droid.org/packages/com.mirfatif.mylocation) (`Lock G[NS]S`) (has other useful features, including the ability to query UnifiedNLP backends)
> 
> I use such an app when I'm out, for a whole variety of reasons (besides for n76's backends to collect data, also other data-collectors (e.g. Tower Collector), [map](//www.openstreetmap.org/) surveying, and not having to wait for GNSS to stabilise when I want to use various (e.g. navigation) apps).
> 
> However, I also use an external battery, so the extra power usage isn't a concern for me. It might be for others.

**Comment by Lee-Carre** [comment]
@n76

> Would it be useful for the data collection to occasionally fire up the GPS in addition to passively monitoring location?

Personally, unless it's optional, then no.

I prefer having control over such things.
* when I want data-collection, I'll toggle GNSS to be perma-active
* when I want power-saving (because I'm not moving, so sampling is pointless, else I wish to conserve battery charge) then I'll leave GNSS inactive

That your backends use the `passive` location provider yields the best of both. I wish more apps would use it (where that makes sense), and have been promoting it to the likes of weather app developers.

I've considered using your backends for general (surveying) data collection of radios, but they log only the minimum for positioning (which makes sense, and don't expect that to change; smaller DB for the efficiency win), whereas I'm something of a greedy data-whore wanting to capture [all characteristics](/n76/wifi_backend/issues/38) & many samples. For network surveying, I use a dedicated collection-only (no processing / filtering, or submitting-to-projects) app (aptly called Network Survey), and (will eventually) process its output separately (e.g. for uploading to projects).

**Comment by gdt** [comment]
I am opposed to DejaVu even having an option to turn on the GNSS receiver.   Part of the point of DejaVu is that it is designed to use very little battery, always.

(Personally, I don't try to force recording.   I just navigate with osmand when going from one place to another, and that results in adequate data.  But the idea of using mylocation or something in the background is a perfectly sensible idea, for those with both spare coulombs and spare heat dissipation ability.)
