### ISSUE TITLE
wiki tinkering parameters

### ISSUE THREAD

**Issue by TameOfGroans** [n76/wifi_backend#9]
are there some informative guidelines for configuring parameters [numeric values]?

some default to 0 [zero]

**Comment by n76** [comment]
If you select a parameter to change the dialog you get has some explanation. If you can assist in coming up with better wording I can certainly update that information.

Off the top, in the GPS parameters:

Required accuracy: Every position report from the GPS includes an estimate of the position error. This number sets the value that the GPS reported position error must be less or equal to for a WiFi scan to be triggered. Basically, it indicates how accurately we must know our present position before we decide to remember the WiFi APs we see at that position.

Sample Distance (meters) and sample interval (seconds): The values passed to the OS when requesting location information. Gives minimum reporting conditions. For example if sample distance is 10 meters then the GPS system will only report a position if it 10 or more meters from the previous report.

WiFi AP assumptions:

Minimum AP range: The backend attempts to determine the actual coverage range of each AP. But if there are not enough samples or the samples are not well placed then the range value can be very small. This number sets the minimum range value that is used in position estimation.

Moved threshold: Unfortunately WiFi APs can move. Either once in a while (e.g. person moves and takes AP with them) or continuously (e.g. WiFi equipped motor bus). One way the back end detects this is to see set a maximum plausible range (moved threshold). If the computed range of an AP exceeds this value we assume that the AP has moved and we should not use it in position computations.

Move guard: The number of plausible samples (ones that do not exceed the moved threshold) that a moved AP must get before we assume that the AP has stopped moving and we can use it in position computations.

**Comment by n76** [comment]
Explanation given, no follow up received.

**Comment by Lee-Carre** [comment]
@TameOfGroans see also #46.
